p = int(input('Digite um número para saber sua tabuada: '))

print(' {} x {:2} = {}'.format(p, 1, p*1))
print(' {} x {:2} = {}'.format(p, 2, p*2))
print(' {} x {:2} = {}'.format(p, 3, p*3))
print(' {} x {:2} = {}'.format(p, 4, p*4))
print(' {} x {:2} = {}'.format(p, 5, p*5))
print(' {} x {:2} = {}'.format(p, 6, p*6))
print(' {} x {:2} = {}'.format(p, 7, p*7))
print(' {} x {:2} = {}'.format(p, 8, p*8))
print(' {} x {:2} = {}'.format(p, 9, p*9))
print(' {} x {:2} = {}'.format(p, 10, p*10))
